// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"klineio/internal/handler"
	"klineio/internal/job"
	"klineio/internal/repository"
	"klineio/internal/server"
	"klineio/internal/service"
	"klineio/pkg/app"
	"klineio/pkg/exchange"
	"klineio/pkg/jwt"
	"klineio/pkg/log"
	"klineio/pkg/notifier"
	"klineio/pkg/server/http"
	"klineio/pkg/sid"
)

// Injectors from wire.go:

func NewWire(conf *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(conf)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(conf, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	httpServer := server.NewHTTPServer(logger, conf, jwtJWT, userHandler)
	exchangePriceRepository := repository.NewExchangePriceRepository(repositoryRepository, logger)
	binanceClient := exchange.NewBinanceClient(logger, conf)
	okexClient := exchange.NewOKEXClient(logger, conf)
	string2 := provideDingTalkWebhookURL(conf)
	dingTalkNotifier := notifier.NewDingTalkNotifier(string2, logger)
	priceMonitorService := service.NewPriceMonitorService(exchangePriceRepository, binanceClient, okexClient, dingTalkNotifier, logger, conf)
	priceMonitorJob := job.NewPriceMonitorJob(priceMonitorService, logger)
	jobJob := job.NewJob(transaction, logger, sidSid, priceMonitorJob)
	userJob := job.NewUserJob(jobJob, userRepository)
	jobServer := server.NewJobServer(logger, userJob)
	appApp := newApp(httpServer, jobServer)
	return appApp, func() {
	}, nil
}

// wire.go:

// provideDingTalkWebhookURL provides the DingTalk webhook URL from config.
func provideDingTalkWebhookURL(conf *viper.Viper) string {
	return conf.GetString("dingtalk.webhook_url")
}

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRedis, repository.NewMongo, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewExchangePriceRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewPriceMonitorService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler)

var jobSet = wire.NewSet(job.NewJob, job.NewUserJob, job.NewPriceMonitorJob)

var exchangeClientSet = wire.NewSet(exchange.NewBinanceClient, exchange.NewOKEXClient)

var notifierSet = wire.NewSet(notifier.NewDingTalkNotifier)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJobServer)

// build App
func newApp(
	httpServer *http.Server,
	jobServer *server.JobServer,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, jobServer), app.WithName("klineio-server"))
}
